tests/test_model.py
Corrected the spelling of "setting" in the comment to ensure clarity and correct usage.
=> Fix typo in comment: "seting" to "setting"

README.md
Changed "The reformatted datasets still has some errors" to "The reformatted datasets still have some errors" for proper subject-verb agreement.
=> Fix typo: Correct "has" to "have" in validation section

model/lora.py
- Added missing articles "the" before "network level" and "layer level" in the Notes section.
=> fix: grammatical errors in LoRALinear class docstring

tests/test_data.py
Corrected the misspelling "instuction" to "instruction" in the comment.
=> fix: Correct typo in comment

utils/validate_data.py
Corrected three instances of the misspelled word "formated" to "formatted" in error messages within the script.
=> Fix typo: "formated" -> "formatted"

utils/validate_data.py
This commit fixes a typo in the verify_size function where the error message for exceeding the maximum number of JSONL lines incorrectly used the singular form "conversation" instead of "conversations" which reflects the correct plural form when referring to multiple lines.
=> fix: typo in error message for JSONL line count verification

tutorials/mistral_finetune_7b.ipynb
Corrected a repeated word "can" in the phrase "you can can run this notebook" within the notebook metadata section. This change improves readability and accuracy in the notebook instructions.
=> fix: remove repeated word in notebook metadata

tutorials/mistral_finetune_7b.ipynb
Corrected the misspelling "lentgh" to "length" in the comments within the notebook.
=> fix: correct spelling of "length" in comments

tutorials/mistral_finetune_7b.ipynb
Corrected the subject-verb agreement error in the sentence "reformat the data into the correct format and skip the cases that *doesn't* have the right format" to "reformat the data into the correct format and skip the cases that *don't* have the right format".
=> fix: correct subject-verb agreement in formatting instructions

tests/test_mixed_precision.py
This commit corrects a typo in the comments of the mixed precision test code. The term "downcasted" has been replaced with the grammatically correct "downcast". This change ensures the comments are accurate and maintain a professional standard.
=> fix: typo in mixed precision test comments

README.md
Corrected the article usage in the README file for GPU recommendation from "a A100 or H100 GPU" to "an A100 or H100 GPU". The article "an" is used before words that start with a vowel sound or a silent 'h'. Since "A100" starts with a vowel sound, "an" is the correct article to use. Although "H100" starts with a consonant sound, "an" is often used for consistency in lists where one item starts with a vowel sound.
=> fix: correct article usage for GPU recommendation

finetune/args.py
Changed "You are have disabled...". to "You have disabled..." to correct a grammatical error.
=> fix: grammar "You are have" to "You have" in logging message

finetune/wrapped_model.py
Corrected typos in the following functions:
1. Fixed  two instances of "seperate" to "separate" in the get_fsdp_policy function.
2. Fixed "randomely" to "randomly" in the initialize_lora_parameters function error message.
3. Fixed "intialized" to "initialized" in the load_model function assertion message.
=> fix: typos in multiple functions

finetune/data/exceptions.py
Corrected a typo in the exception messages where "formated" was changed to "formatted". This change affects the custom exception classes `MessageFormatError`, `ToolCallFormatError`, `FunctionFormatError`, and `ConversationFormatError`.
=> Fix: typo in exception messages: "formated" to "formatted"

finetune/wrapped_model.py
- Corrected "it's" to "its" in the docstring of get_fsdp_policy function.
- Changed "parameter" to "parameters" in the log_train_params function.
=> fix: typos in docstring and logging message

finetune/args.py
Corrected a typo in the warning message of the TrainArgs class. The word "erros" has been changed to "errors" to improve readability and accuracy.
=> fix: typo in TrainArgs warning message

finetune/data/dataset.py
Corrected a typo in the comment within the maybe_chunk_lines function where "shorder" was changed to "shorter" to improve code readability and maintainability.
=> fix: typo in comment: "shorder" to "shorter"

finetune/data/tokenize.py
Corrected "empyt" to "empty" in FunctionFormatError message for function parameters check.
=> fix: typo in function parameters error message

utils/reformat_data_glaive.py
Corrected the misspelling of "formatted" in the print statement within the reformat_jsonl function.
=> fix: typo in reformat_jsonl function output message

finetune/args.py
Corrected "You are have disabled..." to "You have disabled..." as well as "OOM erros" to "OOM errors"
=> fix: grammar and typo in logging message

finetune/data/args.py
Corrected "Assisant" to "Assistant" in multiple places.
Corrected "loose" to "lose" in the comment explaining dynamic chunking.
=> fix: typos in InstructArgs comments

README.md
- Corrected four misspelled instances of the word "formated" to "formatted" in the documentation.
- Added a space after each period to ensure writing standards and readability.
=> fix: Correct typos and formatting

README.md
Corrected the term "MoEs models" to "MoE models" in the documentation for consistency and grammatical accuracy. The acronym "MoE" stands for "Mixture of Experts" and should be used in its singular form followed by "models" to maintain proper grammatical structure.
=> typo: correct "MoEs models" to "MoE models"

finetune/data/dataset.py
Corrected a typo in the comment within the maybe_chunk_lines function. The term "mult-turn" was changed to "multi-turn" for better clarity and accuracy.
=> typo in comment: "mult-turn" to "multi-turn"

finetune/data/dataset.py
Fixed a typo in the comments where "mult-turn" was corrected to "multi-turn".
=> fix: correct spelling in comments

utils/validate_data.py
Fixes an issue introduced in the commit `984ca2dc` where the `else` is misaligned causing the following crash when running data validation tool.
```
Traceback (most recent call last):
File "<frozen runpy>", line 189, in _run_module_as_main
File "<frozen runpy>", line 159, in _get_module_details
File "<frozen importlib._bootstrap_external>", line 1074, in get_code
File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/ec2-user/workspace/mistral/mistral-finetune/utils/validate_data.py", line 113
else:
TabError: inconsistent use of tabs and spaces in indentation
```
=> Fix a mis-aligned else that causes a crash
